"""Vocabulary and URI definitions for GW2-UME."""

from rdflib import Namespace, RDF, RDFS, OWL, XSD

# Namespaces
GW2 = Namespace("https://gw2ume.org/ontology#")
GW2RES = Namespace("https://gw2ume.org/resource/")
SCHEMA = Namespace("http://schema.org/")
SH = Namespace("http://www.w3.org/ns/shacl#")

# Core Classes
CLASS_ITEM = GW2.Item
CLASS_LEGENDARY_WEAPON = GW2.LegendaryWeapon
CLASS_PRECURSOR_WEAPON = GW2.PrecursorWeapon
CLASS_COMPONENT_ITEM = GW2.ComponentItem
CLASS_TROPHY_ITEM = GW2.TrophyItem
CLASS_CRAFTING_MATERIAL = GW2.CraftingMaterial
CLASS_CURATED_COLLECTION = GW2.CuratedCollection
CLASS_COLLECTION_STEP = GW2.CollectionStep
CLASS_COLLECTION_TIER = GW2.CollectionTier
CLASS_MYSTIC_FORGE_RECIPE = GW2.MysticForgeRecipe
CLASS_CRAFTING_RECIPE = GW2.CraftingRecipe
CLASS_CRAFTING_DISCIPLINE = GW2.CraftingDiscipline
CLASS_NPC_VENDOR = GW2.NPCVendor
CLASS_ZONE = GW2.Zone
CLASS_DISCIPLINE_RATING = GW2.DisciplineRating
CLASS_INGREDIENT_QUANTITY = GW2.IngredientQuantity

# Core Properties
PROP_REQUIRES_INGREDIENT = GW2.requiresIngredient
PROP_INGREDIENT_QUANTITY = GW2.ingredientQuantity
PROP_CRAFTED_BY_DISCIPLINE = GW2.craftedByDiscipline
PROP_REQUIRES_DISCIPLINE_RATING = GW2.requiresDisciplineRating
PROP_OBTAINED_FROM_VENDOR = GW2.obtainedFromVendor
PROP_LOCATED_IN_ZONE = GW2.locatedInZone
PROP_HAS_PRECURSOR = GW2.hasPrecursor
PROP_PRECURSOR_TO = GW2.precursorTo
PROP_PART_OF_COLLECTION = GW2.partOfCollection
PROP_COLLECTION_TIER = GW2.tierNumber
PROP_OUTPUT_ITEM = GW2.outputItem
PROP_FORGE_SLOT = GW2.forgeSlot
PROP_ACQUISITION_METHOD = GW2.acquisitionMethod
PROP_CONFIDENCE = GW2.confidenceScore

__all__ = [
    "GW2",
    "GW2RES",
    "SCHEMA",
    "SH",
    "RDF",
    "RDFS",
    "OWL",
    "XSD",
    "CLASS_ITEM",
    "CLASS_LEGENDARY_WEAPON",
    "CLASS_PRECURSOR_WEAPON",
    "CLASS_COMPONENT_ITEM",
    "CLASS_TROPHY_ITEM",
    "CLASS_CRAFTING_MATERIAL",
    "CLASS_CURATED_COLLECTION",
    "CLASS_COLLECTION_STEP",
    "CLASS_COLLECTION_TIER",
    "CLASS_MYSTIC_FORGE_RECIPE",
    "CLASS_CRAFTING_RECIPE",
    "CLASS_CRAFTING_DISCIPLINE",
    "CLASS_NPC_VENDOR",
    "CLASS_ZONE",
    "CLASS_DISCIPLINE_RATING",
    "CLASS_INGREDIENT_QUANTITY",
    "PROP_REQUIRES_INGREDIENT",
    "PROP_INGREDIENT_QUANTITY",
    "PROP_CRAFTED_BY_DISCIPLINE",
    "PROP_REQUIRES_DISCIPLINE_RATING",
    "PROP_OBTAINED_FROM_VENDOR",
    "PROP_LOCATED_IN_ZONE",
    "PROP_HAS_PRECURSOR",
    "PROP_PRECURSOR_TO",
    "PROP_PART_OF_COLLECTION",
    "PROP_COLLECTION_TIER",
    "PROP_OUTPUT_ITEM",
    "PROP_FORGE_SLOT",
    "PROP_ACQUISITION_METHOD",
    "PROP_CONFIDENCE",
]
